# Generated by Django 5.2.5 on 2025-09-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='images',
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
