# Generated by Django 5.2.5 on 2025-09-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_productquantity_images_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="deals/"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="products.productmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "product deal",
                "verbose_name_plural": "product deals",
            },
        ),
    ]
