# Generated by Django 5.2.5 on 2025-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_products',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
