# Generated by Django 5.2.5 on 2025-09-08 14:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='bio_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='bio_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='full_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='full_name_uz',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
