# Generated by Django 5.2.5 on 2025-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_bannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='text_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='text_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
