# Generated by Django 5.2.5 on 2025-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_storemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storemodel',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
