# Generated by Django 5.2.5 on 2025-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_bannermodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
