# Generated by Django 5.2.5 on 2025-09-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_bannermodel_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='link',
            new_name='url',
        ),
    ]
