# Generated by Django 5.2.5 on 2025-09-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_link_bannermodel_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'permissions': [('can_change_status', 'Can change contact status')], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
